/**
 * SEO Health Dashboard - API Module
 * 
 * Generated by scaffold-tool on 2026-01-19
 */

import { Module } from '@nestjs/common';
import { SeoHealthDashboardController } from './seo-health-dashboard.controller';
import { SeoHealthDashboardService } from './seo-health-dashboard.service';
import { PrismaModule } from '../../prisma/prisma.module';

@Module({
  imports: [PrismaModule],
  controllers: [SeoHealthDashboardController],
  providers: [SeoHealthDashboardService],
  exports: [SeoHealthDashboardService],
})
export class SeoHealthDashboardModule {}
