/**
 * SEO Health Dashboard - API Controller
 * 
 * A comprehensive SEO health check tool that analyzes crawl data and identifies issues
 * 
 * Generated by scaffold-tool on 2026-01-19
 */

import {
  Controller,
  Get,
  Post,
  Body,
  Param,
  Query,
  UseGuards,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiParam,
  ApiQuery,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '../../auth/jwt-auth.guard';
import { CurrentUser } from '../../auth/decorators/current-user.decorator';
import { SeoHealthDashboardService } from './seo-health-dashboard.service';
interface SeoHealthDashboardInput {
  projectId: string;
  crawlRunId: string;
  minSeverity?: string;
  includeWarnings?: boolean;
}

@ApiTags('tools/seo-health-dashboard')
@ApiBearerAuth()
@Controller('tools/seo-health-dashboard')
@UseGuards(JwtAuthGuard)
export class SeoHealthDashboardController {
  constructor(private readonly seoHealthDashboardService: SeoHealthDashboardService) {}

  /**
   * POST /tools/seo-health-dashboard/run
   * Execute the tool with given parameters
   */
  @Post('run')
  @ApiOperation({ summary: 'Run SEO Health Dashboard' })
  @ApiResponse({ status: 200, description: 'Tool execution result' })
  @ApiResponse({ status: 400, description: 'Invalid input parameters' })
  @ApiResponse({ status: 403, description: 'Forbidden' })
  async run(
    @CurrentUser('id') userId: string,
    @Body() input: SeoHealthDashboardInput,
  ) {
    return this.seoHealthDashboardService.execute(userId, input);
  }

  /**
   * GET /tools/seo-health-dashboard/history
   * Get execution history for a project
   */
  @Get('history')
  @ApiOperation({ summary: 'Get execution history' })
  @ApiQuery({ name: 'projectId', required: true })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiResponse({ status: 200, description: 'List of previous executions' })
  async getHistory(
    @CurrentUser('id') userId: string,
    @Query('projectId') projectId: string,
    @Query('limit') limit?: number,
  ) {
    return this.seoHealthDashboardService.getHistory(userId, projectId, limit ?? 10);
  }

  /**
   * GET /tools/seo-health-dashboard/result/:executionId
   * Get a specific execution result
   */
  @Get('result/:executionId')
  @ApiOperation({ summary: 'Get execution result' })
  @ApiParam({ name: 'executionId', description: 'Execution ID' })
  @ApiResponse({ status: 200, description: 'Execution result' })
  @ApiResponse({ status: 404, description: 'Execution not found' })
  async getResult(
    @CurrentUser('id') userId: string,
    @Param('executionId') executionId: string,
  ) {
    return this.seoHealthDashboardService.getResult(userId, executionId);
  }

  /**
   * POST /tools/seo-health-dashboard/export
   * Export results in specified format
   */
  @Post('export')
  @ApiOperation({ summary: 'Export results' })
  @ApiResponse({ status: 200, description: 'Exported data' })
  async exportResults(
    @CurrentUser('id') userId: string,
    @Body() body: { executionId: string; format: 'csv' | 'json' | 'pdf' },
  ) {
    return this.seoHealthDashboardService.exportResults(userId, body.executionId, body.format);
  }
}
