'use client';

/**
 * SEO Health Dashboard - Dashboard Page
 * 
 * A comprehensive SEO health check tool that analyzes crawl data and identifies issues
 * 
 * Generated by scaffold-tool on 2026-01-19
 */

import { useState } from 'react';
import { Protected } from '@/components/Protected';
import { AppShell } from '@/components/AppShell';
import { useToast } from '@/components/Toast';
import { apiFetch } from '@/lib/api';

// ============================================
// TYPES
// ============================================

interface SeoHealthDashboardInput {
  projectId: string;
  crawlRunId: string;
  minSeverity?: string;
  includeWarnings?: boolean;
}

interface SeoHealthDashboardOutput {
  summary: Record<string, number>;
  results: Array<Record<string, unknown>>;
  generatedAt: string;
}

// ============================================
// MAIN CONTENT
// ============================================

function SeoHealthDashboardContent() {
  const toast = useToast();
  
  // Input state
  const [input, setInput] = useState<SeoHealthDashboardInput>({
    projectId: '',
    crawlRunId: '',
    minSeverity: '',
    includeWarnings: true,
  });
  
  // Output state
  const [output, setOutput] = useState<SeoHealthDashboardOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'input' | 'results'>('input');

  const handleRun = async () => {
    setIsLoading(true);
    try {
      const result = await apiFetch<SeoHealthDashboardOutput>('/tools/seo-health-dashboard/run', {
        method: 'POST',
        body: input,
      });
      setOutput(result);
      setActiveTab('results');
      toast.success('Analysis complete!');
    } catch (err) {
      console.error('Failed to run tool:', err);
      toast.error('Failed to run analysis');
    } finally {
      setIsLoading(false);
    }
  };

  const handleExport = async (format: 'csv' | 'json' | 'pdf') => {
    if (!output) return;
    try {
      // TODO: Implement export with execution ID
      toast.success(`Exported as ${format.toUpperCase()}`);
    } catch (err) {
      toast.error('Export failed');
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">SEO Health Dashboard</h1>
          <p className="text-gray-500 mt-1">
            A comprehensive SEO health check tool that analyzes crawl data and identifies issues
          </p>
        </div>
        <div className="flex items-center gap-3">
          {output && (
            <div className="flex gap-2">
              <button
                onClick={() => handleExport('csv')}
                className="px-3 py-1.5 text-sm bg-gray-100 hover:bg-gray-200 rounded-lg"
              >
                📄 CSV
              </button>
              <button
                onClick={() => handleExport('json')}
                className="px-3 py-1.5 text-sm bg-gray-100 hover:bg-gray-200 rounded-lg"
              >
                🔧 JSON
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200">
        <nav className="flex gap-4">
          <button
            onClick={() => setActiveTab('input')}
            className={`py-3 px-1 border-b-2 font-medium text-sm ${
              activeTab === 'input'
                ? 'border-blue-500 text-blue-600'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            }`}
          >
            ⚙️ Configuration
          </button>
          <button
            onClick={() => setActiveTab('results')}
            className={`py-3 px-1 border-b-2 font-medium text-sm ${
              activeTab === 'results'
                ? 'border-blue-500 text-blue-600'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            }`}
          >
            📊 Results {output ? `(${output.results.length})` : ''}
          </button>
        </nav>
      </div>

      {/* Tab Content */}
      {activeTab === 'input' && (
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Input Parameters</h2>
          
          <div className="space-y-4">
            {/* Project */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Project *
              </label>
              <input
                type="text"
                value={input.projectId}
                onChange={(e) => setInput({ ...input, projectId: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                placeholder="Select the project to analyze"
              />
            </div>

            {/* Crawl Run */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Crawl Run *
              </label>
              <input
                type="text"
                value={input.crawlRunId}
                onChange={(e) => setInput({ ...input, crawlRunId: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                placeholder="Select the crawl run to analyze"
              />
            </div>

            {/* Minimum Severity */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Minimum Severity
              </label>
              <select
                value={input.minSeverity}
                onChange={(e) => setInput({ ...input, minSeverity: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select...</option>
                <option value="LOW">Low and above</option>
                <option value="MEDIUM">Medium and above</option>
                <option value="HIGH">High and above</option>
                <option value="CRITICAL">Critical only</option>
              </select>
              <p className="text-xs text-gray-500 mt-1">Filter issues by minimum severity</p>
            </div>

            {/* Include Warnings */}
            <div className="flex items-center gap-3">
              <input
                type="checkbox"
                checked={input.includeWarnings}
                onChange={(e) => setInput({ ...input, includeWarnings: e.target.checked })}
                className="w-4 h-4 text-blue-600 border-gray-300 rounded"
              />
              <label className="text-sm font-medium text-gray-700">
                Include Warnings
              </label>
              <span className="text-xs text-gray-500">Include warning-level issues in the report</span>
            </div>
          </div>

          <div className="mt-6 pt-6 border-t border-gray-200">
            <button
              onClick={handleRun}
              disabled={isLoading}
              className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 flex items-center gap-2"
            >
              {isLoading ? (
                <>
                  <span className="animate-spin">⚙️</span>
                  Running...
                </>
              ) : (
                <>
                  ▶️ Run Analysis
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {activeTab === 'results' && (
        <div className="space-y-6">
          {output ? (
            <>
              {/* Summary Cards */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-white rounded-xl border border-gray-200 p-4">
                  <p className="text-sm text-gray-500">Health Score</p>
                  <p className="text-2xl font-bold text-gray-900">
                    {output.summary.healthScore ?? '-'} <span className="text-sm font-normal text-gray-500">points</span>
                  </p>
                </div>
                <div className="bg-white rounded-xl border border-gray-200 p-4">
                  <p className="text-sm text-gray-500">Critical Issues</p>
                  <p className="text-2xl font-bold text-gray-900">
                    {output.summary.criticalIssues ?? '-'} <span className="text-sm font-normal text-gray-500">issues</span>
                  </p>
                </div>
                <div className="bg-white rounded-xl border border-gray-200 p-4">
                  <p className="text-sm text-gray-500">Pages with Issues</p>
                  <p className="text-2xl font-bold text-gray-900">
                    {output.summary.pagesWithIssues ?? '-'} <span className="text-sm font-normal text-gray-500">pages</span>
                  </p>
                </div>
                <div className="bg-white rounded-xl border border-gray-200 p-4">
                  <p className="text-sm text-gray-500">Clean Pages</p>
                  <p className="text-2xl font-bold text-gray-900">
                    {output.summary.cleanPagesPct ?? '-'} <span className="text-sm font-normal text-gray-500">%</span>
                  </p>
                </div>
              </div>

              {/* Results Table */}
              <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-200">
                  <h3 className="font-semibold text-gray-900">Results</h3>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                          ID
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                          Data
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                      {output.results.slice(0, 50).map((row, idx) => (
                        <tr key={idx} className="hover:bg-gray-50">
                          <td className="px-6 py-4 text-sm text-gray-900">
                            {(row as { id?: string }).id || idx}
                          </td>
                          <td className="px-6 py-4 text-sm text-gray-500">
                            <pre className="text-xs">{JSON.stringify(row, null, 2)}</pre>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {output.results.length > 50 && (
                  <div className="px-6 py-3 bg-gray-50 text-sm text-gray-500">
                    Showing 50 of {output.results.length} results
                  </div>
                )}
              </div>

              {/* Generated At */}
              <p className="text-sm text-gray-400 text-right">
                Generated at {new Date(output.generatedAt).toLocaleString()}
              </p>
            </>
          ) : (
            <div className="bg-white rounded-xl border border-gray-200 p-12 text-center">
              <div className="text-4xl mb-4">📊</div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">No Results Yet</h3>
              <p className="text-gray-500 mb-4">
                Configure your parameters and run the analysis to see results.
              </p>
              <button
                onClick={() => setActiveTab('input')}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Go to Configuration
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ============================================
// PAGE EXPORT
// ============================================

export default function SeoHealthDashboardPage() {
  return (
    <Protected>
      <AppShell>
        <SeoHealthDashboardContent />
      </AppShell>
    </Protected>
  );
}
